### ISSUE TITLE
NO SLN FILE ME DONT KNOW HOW TO OPEN

### ISSUE THREAD

**Issue by loanselot** [GrowtopiaNoobs/Growtopia_ItemsDecoder#1]
NO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPENNO SLN FILE ME DONT KNOW HOW TO OPEN

**Comment by flossboss** [comment]
Lol

**Comment by Ipadtopia** [comment]
lol

**Comment by Mempler** [comment]
lol

**Comment by iProgramMC** [comment]
lol

**Comment by GrowtopiaNoobs** [comment]
There wont be any. Please create sln project yourself and import all code.

**Comment by loanselot** [comment]
I DENY THAT
