### ISSUE TITLE
I need help with an error when building

### ISSUE THREAD

**Issue by Hard69** [GrowtopiaNoobs/Growtopia_ItemsDecoder#10]
![Item dat decoder - Microsoft Visual Studio 12_29_2019 8_22_44 AM](https://user-images.githubusercontent.com/59339614/71559579-94a86d80-2a14-11ea-96df-c022965309d4.png)

**Comment by Mempler** [comment]
^ that's an issue with your Project setup. not Executable, as it compiles fine for me using GCC, LLVM and VS2019

**Comment by Hard69** [comment]
Can u help me with that whatever I do doesn't work for me........

**Comment by Hard69** [comment]
I managed to do it thanks for everything ;D

**Comment by Mempler** [comment]
Please close this issue, Thanks.
