### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by GrowStone** [GrowtopiaNoobs/Growtopia_ItemsDecoder#11]
For users having issue compiling the decoder on Windows, do this:

1. Add `#include <_mingw.h>` to the top of the script
2. If compiling still doesn't work, open CMD and downgrade mingw by using the following command
`mingw-get upgrade mingwrt=5.2.1`

**Comment by whotakeaurumk** [comment]
Can you help me in Discord i did what u said but it still doesnt work

**Comment by GrowStone** [comment]
Then please use trial and error to fix the issue.
