### ISSUE TITLE
I dont know how to build lol

### ISSUE THREAD

**Issue by whotakeaurumk** [GrowtopiaNoobs/Growtopia_ItemsDecoder#13]
I import items.dat but know i dont know how to build i run code and then? IK Its cringe for u

**Comment by WoofHax** [comment]
g++ items_decoder.cpp

**Comment by whotakeaurumk** [comment]
So what will i do with ? i opened project with visual studio and i dont know how to build

**Comment by WoofHax** [comment]
You can use termux to build this Project

**Comment by atomiclucky** [comment]
download mingw for windows and use cmd

**Comment by ardakurucim** [comment]
create new project damn

**Comment by whotakeaurumk** [comment]
> create new project damn

Yemin et aq

**Comment by atomiclucky** [comment]
brb gonna make an user called linuxman

**Comment by ardakurucim** [comment]
@whotakeaurumk özürlüsün galiba amk niye soruyosun o zaman

**Comment by whotakeaurumk** [comment]
> @whotakeaurumk özürlüsün galiba amk niye soruyosun o zaman

aptal orospu evladı ben diyorumki idk how to build sen diyorsunki just create a new project damn çok mu komiksin amk ben bilmiyordum ya sağol iki gıdım kodlama ve ingilizcenle şurada boş boş yorum yapma siktir git

**Comment by ardakurucim** [comment]
@whotakeaurumk aptalın evladı buildlemek için proje oluşturcaksın ne kadar salaksın

**Comment by whotakeaurumk** [comment]
> @whotakeaurumk aptalın evladı buildlemek için proje oluşturcaksın ne kadar salaksın

Bir sik bilmiyorsan siktir git uğraştırma beni senle.

**Comment by ardakurucim** [comment]
![anladım](https://user-images.githubusercontent.com/48387425/72001163-dd062d80-3255-11ea-9dfc-70288ea50405.PNG)

**Comment by whotakeaurumk** [comment]
So then idiot?

**Comment by ardakurucim** [comment]
@whotakeaurumk discord?
