### ISSUE TITLE
where compiler?

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/Growtopia_ItemsDecoder#14]

**Comment by GrowStone** [comment]
You need to compile it yourself.

**Comment by GuckTubeYT** [comment]
But how, without sln

**Comment by flossboss** [comment]
Make sln yourself

**Comment by GuckTubeYT** [comment]
how lol

**Comment by NotDark** [comment]
> how lol

google visual studio how to make new c++ project

**Comment by JadlionHD** [comment]
make an empty project, then import all files to the project, like hpp and cpp.

**Comment by GuckTubeYT** [comment]
> make an empty project, then import all files to the project, like hpp and cpp.

Didnt work, please @JadlionHD make sln pls

**Comment by DrOreo002** [comment]
I put a tutorial on how to build it already. And I'm also sure that you have installed g++ since ur asking for .sln project, so it should work for you.
