### ISSUE TITLE
How to convert .json to .dat

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/Growtopia_ItemsDecoder#15]
I Just Decode items.dat, but how to encode json?

**Comment by DrOreo002** [comment]
Re-write the byte at the exact same order. Don't also forget to encrypt the name using the exact same key, use this method
https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1127#issuecomment-574330945 (Provided by Ama)

~ Good luck!

**Comment by GuckTubeYT** [comment]
> 
> 
> Re-write the byte at the exact same order. Don't also forget to encrypt the name using the exact same key, use this method
> [GrowtopiaNoobs/GrowtopiaServer#1127 (comment)](https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1127#issuecomment-574330945) (Provided by Ama)
> 
> ~ Good luck!

tutorial pls

**Comment by DrOreo002** [comment]
> > Re-write the byte at the exact same order. Don't also forget to encrypt the name using the exact same key, use this method
> > [GrowtopiaNoobs/GrowtopiaServer#1127 (comment)](https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1127#issuecomment-574330945) (Provided by Ama)
> > ~ Good luck!
> 
> tutorial pls

?, I gave you the information already, stop begging for others to make it work for you. I know you already knew how to code / programming, use ur brain.

**Comment by GuckTubeYT** [comment]
but i still didnt know

**Comment by GuckTubeYT** [comment]
can you explain?

**Comment by cwkhawand** [comment]
If you don't have basic knowledge on how C++ works, then I recommend you go learn the basics first.

**Comment by lixorhaxz** [comment]
@DrOreo002 
![Screenshot_2020-01-19-07-23-33-204_com microsoft rdc android](https://user-images.githubusercontent.com/47329758/72671910-db760a00-3a8c-11ea-9fba-abc233b6721c.png)
I Got This error

**Comment by DrOreo002** [comment]
> If you don't have basic knowledge on how C++ works, then I recommend you go learn the basics first.

He won't listen to your recommendation, because hes just a 13 yr old boy who wants to get rich by making gt server



> @DrOreo002
> ![Screenshot_2020-01-19-07-23-33-204_com microsoft rdc android](https://user-images.githubusercontent.com/47329758/72671910-db760a00-3a8c-11ea-9fba-abc233b6721c.png)
> I Got This error

Lmao idiot. You literally just copy the paste the code lol, thats not how it works /fp. Go learn cpp first before jumping to this kind of thing :)

If cpp is too hard for ya, you can try my Java item.dat reader.

**Comment by GuckTubeYT** [comment]
> 
> 
> > If you don't have basic knowledge on how C++ works, then I recommend you go learn the basics first.
> 
> He won't listen to your recommendation, because hes just a 13 yr old boy who wants to get rich by making gt server
> 
> > @DrOreo002
> > ![Screenshot_2020-01-19-07-23-33-204_com microsoft rdc android](https://user-images.githubusercontent.com/47329758/72671910-db760a00-3a8c-11ea-9fba-abc233b6721c.png)
> > I Got This error
> 
> Lmaoooooo. You literally just copy the paste the code lol, thats not how it works /fp. Go learn cpp first before jumping to this kind of thing :)
> 
> If cpp is too hard for ya, you can try my Java item.dat reader. It has the basic of reading so writing the data shouldn't be hard for ya :D

but when i use your item.dat reader java, and then error, i got stuck

**Comment by SxRnArTz** [comment]
> Re-write the byte at the exact same order. Don't also forget to encrypt the name using the exact same key, use this method
> [GrowtopiaNoobs/GrowtopiaServer#1127 (comment)](https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1127#issuecomment-574330945) (Provided by Ama)
> 
> ~ Good luck!

um this doesnt exist atm can u say new way?
