### ISSUE TITLE
"Item are unordered!" error 5 times

### ISSUE THREAD

**Issue by ReimarPB** [GrowtopiaNoobs/Growtopia_ItemsDecoder#18]
When I run the program, i get the following output:
```
Decoding items data...
Item are unordered!
Item are unordered!
Item are unordered!
Item are unordered!
Item are unordered!
```
The items.dat file was copied straight from Growtopia's cache folder and I'm running Windows 10. Does anyone know how to fix this?

**Comment by GrowStone** [comment]
Go figure it our yourself, it's not that hard to notice the difference.

**Comment by Alexander9673** [comment]
@ReimarPB do you have discord? if so pm me i want to as something
`_alexander#9673`

**Comment by ReimarPB** [comment]
@GrowStone difference between what?
@Alexander9673 I sent you a friend req

**Comment by iProgramMC** [comment]
@ReimarPB you need to decompress and recompress the items.dat. A Python script is available at https://github.com/iProgramMC/Growtopia_ItemsDatReader/blob/master/decompress_items.dat.py and https://github.com/iProgramMC/Growtopia_ItemsDatEncoder/blob/master/compress_items.dat.py.
