### ISSUE TITLE
How about the encode?

### ISSUE THREAD

**Issue by delta168** [GrowtopiaNoobs/Growtopia_ItemsDecoder#27]

**Comment by GuckTubeYT** [comment]
Make it urself

**Comment by DrOreo002** [comment]
The order is the same as decoding, but its writing instead of reading. You'll also need to encrypt the item name with the secret key, pretty sure its cyclic hash, you can find it online

**Comment by GuckTubeYT** [comment]
https://github.com/iProgramMC/Growtopia_ItemsDatEncoder

**Comment by delta168** [comment]
> https://github.com/iProgramMC/Growtopia_ItemsDatEncoder

Hmm I think it not work for new version.
