### ISSUE TITLE
[Error] how to fix about std::bad_alloc

### ISSUE THREAD

**Issue by WoofHax** [GrowtopiaNoobs/Growtopia_ItemsDecoder#5]
my output 
terminate called after throwing an instance of 'std::bad_alloc'

**Comment by GrowtopiaNoobs** [comment]
Do you have items.dat in same folder as decoder? If so, can you please share your items.dat?

**Comment by WoofHax** [comment]
dm my discord bengt#5300

Linux method is working all is fine so I can close this issues 

![IMG_20191229_015636](https://user-images.githubusercontent.com/52075701/71547730-cacafa80-29de-11ea-85f1-77e669cec08d.jpg)
